### ISSUE TITLE
It only send every 2 seconds one frame

### ISSUE THREAD

**Issue by Gojobriel** [NPCat/bad-apple-bot#13]
When I start the bot it doesnt send all the frames but only every few seconds one single frame

**Comment by CodingAna** [comment]
As mentioned in his video, discord.py is limited to a few calls per sec so he sped up the video.

**Comment by 1vs9-standart** [comment]
you can change 
TIMEOUT = 1/((int(CLIP_FRAMES/4)+1)/CLIP_LENGTH)*18
on
TIMEOUT = 1/((int(CLIP_FRAMES/4)+1)/CLIP_LENGTH)*7
1 frame every 0.8 seconds 

changing below 0.5 is probably not desirable
