### ISSUE TITLE
Everything set up, but not run

### ISSUE THREAD

**Issue by 7venyk** [NPCat/bad-apple-bot#20]
I set everything up following the easy guide commented by 1vs9-standar 
I try to run and I get this error

```
Traceback (most recent call last):
  File "C:\Users\VenyK\Desktop\bad-apple-bot-main\bad-apple-discord-player.py", line 61, in <module>
    client = discord.Client('ODIzODA1NzEwMDQyMzk4NzYx.YFmK2g.1njeNFihMrKssdPskXXXXXXXXXX')
TypeError: __init__() takes 1 positional argument but 2 were given
```

**Comment by Cosmin-Clucerescu** [comment]
You have to edit line 97 where there's
```
client.run('')#<--- Put bot token here
```
Not that line.
Also note that that token is secret and you shouldn't show it to everyone, you probably want to delete it now that you made it public.
